nitrictech/docs

docs/installation.mdx
To verify type nitric instead of nitric --version
=> refactor: Update installation

docs/quick-start.mdx
update quick-start with cli updates and functions changed to services
=> refactor: update quick-start

doc.config.json, test/schema.json
Website PR should be merged in conjunction with this one.
=> feature: ability to add sidebars to website docs

docs/secrets.mdx
Hey Mal, rather than add to many comments to the PR, here are some suggested edits (take them or leave them). If the typos are fixed at a minimum I'll add my approval.
https://github.com/nitrictech/docs/pull/54
=> docs: suggested edits to the secrets doc

docs/documents.mdx, docs/events.mdx, docs/queues.mdx, docs/quick-start.mdx, docs/secrets.mdx, docs/storage.mdx
WIP - everyone feel free to chip in and add the snippets.
=> docs: start adding snippets

docs/reference/project/schedules.mdx
This PR relies on https://github.com/nitrictech/cli/pull/202 being merged.
=> fix: add quotes to encapsulate expression in example.

docs/reference/api/queues/send-tasks.mdx, docs/reference/project/stack.mdx
=> Merge Develop into Main

docs/reference/api/events/_index.mdx
=> chore: minor docs typo

doc.config.json, docs/reference/azure/_index.mdx, docs/reference/azure/apis.mdx, docs/reference/azure/collections.mdx, docs/reference/azure/secrets.mdx, docs/reference/azure/storage.mdx, docs/reference/azure/topics.mdx
Some proposed edits to your PR
=> docs(azure): edits for detail and corrections

docs/apis/_index.md, docs/collections/_index.md, docs/messaging/queues.md, docs/messaging/topics.md, docs/secrets/_index.md, docs/storage/_index.md
Include more details and fix minor issues in docs
=> docs: minor edits

docs/secrets/_index.md
version is a property not function.
=> chore: change version() to version

docs/concepts.mdx
Fix publish to match NitricEvent.
=> chore: fix concepts example

docs/support/upgrade.md
Remove statement about yaml files.
=> chore: new cli does now have a nitric.yaml file

doc.config.json, docs/guides/api-with-nextjs.md, docs/guides/github-actions.md, docs/guides/nitric-and-supabase.md, docs/guides/serverless-api-with-planetscale-and-prisma.md, docs/guides/serverless-rest-api-example.md
minor refactor of page names 
Co-authored-by: jye.cusch@nitric.io
=> chore: add title and description to guides

.github/workflows/test.yaml
Closes #295
Dependent on PR release in website repo
=> test: add broken website link tests

docs/reference/storage/files.md, docs/storage/_index.md
TODO:
Remove from draft once feature is deployed.
=> Add documentation for listing files in a bucket.

doc.config.json
Add missing reference link for bucket.files()
=> add bucket.files() reference

doc.config.json, docs/resources-overview.md
Still need to add multiple language examples/support, but I think this will be useful to link in our SDK errors.
=> Add resources overview document.

dictionary.txt, doc.config.json, docs/reference/nodejs/v0/storage/bucket-file-downloadurl.md, docs/reference/nodejs/v0/storage/bucket-file-uploadurl.md
sign-url is deprecated, so removing from docs
=> fix: use download url and upload url

dictionary.txt, docs/guides/serverless-rest-api-example.md
This is currently in a single file
=> python rest API guide

docs/reference/csharp/v0/storage/bucket.md
Closes: https://github.com/nitrictech/docs/issues/375
=> fix: update signUrl reference to download and upload references

docs/deployment.md, docs/language-support.md, docs/reference/cli/index.md, docs/reference/cli/stacks.md
Closes: https://github.com/nitrictech/docs/issues/383
=> feat: update documentation with new provider config

docs/apis.md
- added details on security definitions
- removed redundant code and comments
- provide more specific details where possible
- general grammar and content updates
=> docs: improve APIs doc

cypress/e2e/broken-links.cy.ts, dictionary.txt, src/nav.config.ts, src/pages/guides/getting-started/nodejs/nestjs.mdx, src/pages/reference/nodejs/v0/http/http.mdx
Relies on the HTTP support to be supported in the node SDK
Closes: https://github.com/nitrictech/nitric-website/issues/1112
=> feat: add http docs and guide for nestjs integration

dictionary.txt, src/nav.config.ts, src/pages/websockets.mdx
depends on: https://github.com/nitrictech/node-sdk/pull/196
=> docs: Websockets

src/components/Footer.tsx, src/pages/contributions.mdx
Fixes a repetitive section and adds the discord link
=> update contributions page

dictionary.txt, src/pages/reference/providers.mdx, src/pages/reference/providers/aws/apis.mdx, src/pages/reference/providers/aws/collections.mdx, src/pages/reference/providers/aws/configuration.mdx, src/pages/reference/providers/aws/queues.mdx, src/pages/reference/providers/aws/schedules.mdx, src/pages/reference/providers/aws/secrets.mdx, src/pages/reference/providers/aws/storage.mdx, src/pages/reference/providers/aws/topics.mdx, src/pages/reference/providers/azure.mdx, src/pages/reference/providers/azure/apis.mdx, src/pages/reference/providers/azure/collections.mdx, src/pages/reference/providers/azure/queues.mdx, src/pages/reference/providers/azure/schedules.mdx, src/pages/reference/providers/azure/secrets.mdx, src/pages/reference/providers/azure/storage.mdx, src/pages/reference/providers/azure/topics.mdx, src/pages/reference/providers/gcp.mdx, src/pages/reference/providers/gcp/apis.mdx, src/pages/reference/providers/gcp/collections.mdx, src/pages/reference/providers/gcp/configuration.mdx, src/pages/reference/providers/gcp/queues.mdx, src/pages/reference/providers/gcp/schedules.mdx, src/pages/reference/providers/gcp/secrets.mdx, src/pages/reference/providers/gcp/storage.mdx, src/pages/reference/providers/gcp/topics.mdx
Closes: https://github.com/nitrictech/nitric-website/issues/1184
=> feat: update provider documentation with more details

src/nav.config.ts, src/pages/guides/getting-started/gitlab-ci.mdx
Closes: https://github.com/nitrictech/nitric/issues/503
=> feat: add gitlab ci guide

src/pages/assets/env.mdx
Not 100% sold on having this under assets, however it will still get picked up by the search.
=> add nitric system environment variables

.github/workflows/deploy.yaml, prisma/migrations/20231115050520_add_comment/migration.sql, prisma/schema.prisma, src/components/Button.tsx, src/components/FeedbackForm.tsx, src/components/Footer.tsx, src/pages/api/feedback.ts
adds new textarea for users to send comments and a new feedback option
=> feat: add page feedback comments

dictionary.txt, src/pages/guides/getting-started/go/serverless-rest-api-example.mdx, src/pages/guides/getting-started/jvm/serverless-rest-api-example.mdx, src/pages/guides/getting-started/local-dashboard.mdx, src/pages/guides/getting-started/nodejs/api-with-nextjs.mdx, src/pages/guides/getting-started/nodejs/expressjs.mdx, src/pages/guides/getting-started/nodejs/fastify.mdx, src/pages/guides/getting-started/nodejs/graphql.mdx, src/pages/guides/getting-started/nodejs/nestjs.mdx, src/pages/guides/getting-started/nodejs/nitric-and-supabase.mdx, src/pages/guides/getting-started/nodejs/serverless-api-with-planetscale-and-prisma.mdx, src/pages/guides/getting-started/nodejs/serverless-rest-api-example.mdx, src/pages/guides/getting-started/nodejs/stripe.mdx, src/pages/guides/getting-started/nodejs/twilio.mdx, src/pages/guides/getting-started/nodejs/websockets.mdx, src/pages/guides/getting-started/python/create-histogram.mdx, src/pages/guides/getting-started/python/graphql.mdx, src/pages/guides/getting-started/python/serverless-rest-api-example.mdx, src/pages/guides/getting-started/python/text-prediction.mdx, src/pages/guides/getting-started/quickstart.mdx, src/pages/reference/cli/stacks.mdx
doc updates for nitric new and stack new commands
=> update docs to match new cli updates

src/pages/guides/getting-started/azure-pipelines.mdx
=> Fix azure pipelines guide

src/pages/reference/providers/gcp/configuration.mdx
resolves: [494](https://github.com/nitrictech/docs/issues/494)
=> docs: update links in GCP stack comments

src/pages/guides/getting-started/nodejs/stripe.mdx
Closes: https://github.com/nitrictech/docs/issues/497
=> fix boolean logic issue in stripe guide

src/pages/assets/access-control.mdx, src/pages/guides/getting-started/concepts.mdx, src/pages/guides/getting-started/nodejs/api-with-nextjs.mdx, src/pages/guides/getting-started/nodejs/testing.mdx, src/pages/keyvalue.mdx, src/pages/reference/cli.mdx, src/pages/reference/nodejs/websocket/websocket-on.mdx, src/pages/reference/nodejs/websocket/websocket-send.mdx, src/pages/reference/providers/aws/keyvalue.mdx, src/pages/reference/providers/azure/keyvalue.mdx, src/pages/reference/python/websocket/websocket-send.mdx
All done except upgrade guide which will be a separate PR
=> replace references to collections with kv

src/components/Layout.tsx, src/components/Libraries.tsx, src/nav.config.ts, src/pages/guides/getting-started/quickstart.mdx
revert this once python v1 is released
=> temporary removal of v1 python docs

dictionary.txt, src/components/Layout.tsx, src/components/Libraries.tsx, src/nav.config.ts, src/pages/apis.mdx, src/pages/guides/getting-started/concepts.mdx, src/pages/guides/getting-started/deployment.mdx, src/pages/guides/getting-started/nodejs/expressjs.mdx, src/pages/guides/getting-started/nodejs/fastify.mdx, src/pages/guides/getting-started/nodejs/websockets.mdx, src/pages/guides/getting-started/quickstart.mdx, src/pages/http.mdx, src/pages/keyvalue.mdx, src/pages/reference/cli.mdx, src/pages/reference/nodejs/keyvalue/keyvalue-keys.mdx, src/pages/reference/nodejs/keyvalue/keyvalue.mdx, src/pages/reference/providers/aws/configuration.mdx, src/pages/reference/providers/gcp/configuration.mdx, src/pages/reference/python/keyvalue/keyvalue-delete.mdx, src/pages/reference/python/keyvalue/keyvalue-keys.mdx, src/pages/reference/python/keyvalue/keyvalue-set.mdx, src/pages/reference/python/topic/topic-publish.mdx, src/pages/reference/python/topic/topic-subscribe.mdx, src/pages/support/upgrade/index.mdx, src/pages/websockets.mdx
relies on https://github.com/nitrictech/node-sdk/pull/223
=> apply 1.1 kv changes

src/pages/reference/providers/gcp/secrets.mdx
Fixed typo with the provider name.
=> Update secrets.mdx - fix typo with the provider name

src/pages/reference/python/api/api-post.mdx
=> Update api-post.mdx - fix typo for HTTP Method

src/pages/apis.mdx
Fixed typo in security definition override flow.
=> Update apis.mdx - fix typo in security definition override flow

src/pages/guides/getting-started/python/serverless-rest-api-example.mdx, src/pages/reference/python/storage/bucket-file-delete.mdx, src/pages/reference/python/storage/bucket-file-downloadurl.mdx, src/pages/reference/python/storage/bucket-file-read.mdx, src/pages/reference/python/storage/bucket-file-uploadurl.mdx, src/pages/reference/python/storage/bucket-file-write.mdx, src/pages/reference/python/storage/bucket-file.mdx, src/pages/reference/python/storage/bucket-files.mdx, src/pages/reference/python/storage/bucket-on.mdx, src/pages/reference/python/storage/bucket.mdx
Merge after: https://github.com/nitrictech/python-sdk/pull/132
=> docs(python): new bucket permissions

dictionary.txt, src/nav.config.ts, src/pages/reference/preview-features/index.mdx, src/pages/reference/providers/install/docker.mdx
Merge after https://github.com/nitrictech/cli/pull/722 since this documents that preview feature
=> docs: document preview features

src/nav.config.ts, src/pages/reference/nodejs/http/http.mdx
=> fix: node http reference docs

package.json, scripts/collect-assets.js, src/assets/cli-usage.txt, src/mdx/remark.mjs, src/pages/reference/cli.mdx, src/pages/reference/cli/stacks.mdx, yarn.lock
Within the vercel environment, this will install the CLI and output the nitric help command into a txt file for the build.
=>  feat: auto generate cli help snippet and update cli docs

src/nav.config.ts
not sure on positioning here, added it just after what is nitric.
=> add /infrastructure-from-code

src/pages/reference/providers/gcp/configuration.mdx
This reverts commit f59e09dccb7e31792927c5371c942756f0b33633.
=> Revert "docs: Update GCP configuration reference for GPU config (#606)"

package.json, yarn.lock
=> fix: upgrade next to 14.2.21
