docs/installation.mdx

Error received if sh is used with #!/bin/sh as a comment in install file.

chore: change sh to bash

---

docs/apis/_index.md
docs/reference/api/api-route-all.mdx

Meant as a solution to this issue:
https://github.com/nitrictech/node-sdk/issues/117
Don't need to do Auth Middleware in particular, as the api security definitions is now an included feature in base APIs.

feat: Add api middleware information to base API docs to increase visibility

---

docs/guides/serverless-api-with-planetscale-and-prisma.md

Hey folks 👋  
We have made some changes to the feature previously known as Referential Integrity. 
1. This feature has been renamed to “****Relation mode”**** in Prisma 4.5.0. 
2. This feature will become [Generally Available](https://www.prisma.io/docs/about/prisma/releases#generally-available-ga) in Prisma 4.7.0, which will be released next Tuesday (29th November).
You can learn more about this change in the [documentation](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/relation-mode) and [release notes](https://github.com/prisma/prisma/releases).
Making this PR to update the docs and to give you a heads-up on this change. 
If you have any questions or if any further modifications are needed, please let me know. Additionally, please only merge this _after_ Prisma …

Update prisma referential Integrity

---

src/pages/guides/getting-started/nodejs/stripe.mdx
src/pages/guides/getting-started/python/create-histogram.mdx
src/pages/guides/getting-started/python/graphql.mdx
src/pages/guides/getting-started/python/serverless-rest-api-example.mdx
src/pages/guides/getting-started/python/text-prediction.mdx
src/pages/reference/python/v0/storage/bucket-on.mdx
src/pages/storage.mdx

Only use `async` for handler definitions. This change is compatible with the current SDK version and represents the restrictions of the upcoming version which removes support for non-async handlers.

docs(python): updates to  match upcoming SDK changes

---

src/pages/reference/python/keyvalue/keyvalue.mdx

Fixed typos with the description of available permissions for the Key-Value Store.

Update keyvalue.mdx - fix typos with permissions

---

src/pages/guides/getting-started/python/serverless-rest-api-example.mdx
src/pages/reference/python/storage/bucket-file-delete.mdx
src/pages/reference/python/storage/bucket-file-downloadurl.mdx
src/pages/reference/python/storage/bucket-file-read.mdx
src/pages/reference/python/storage/bucket-file-uploadurl.mdx
src/pages/reference/python/storage/bucket-file-write.mdx
src/pages/reference/python/storage/bucket-file.mdx
src/pages/reference/python/storage/bucket-files.mdx
src/pages/reference/python/storage/bucket-on.mdx
src/pages/reference/python/storage/bucket.mdx

1. Fixed permissions for storage/bucket in Python reference docs.
Permissions should be as per the ones defined in the [codebase](https://github.com/nitrictech/python-sdk/blob/36989934a6f961985ad75288409bb2a2f330207b/nitric/resources/buckets.py#L175).
2. Fixed issues with datetime.utcnow() deprecation and data format for the 'expiry' parameter.
The 'expiry' parameter expects the value to be of timedelta format.
If the same is not passed, the sign_url method produces a
GRPCError 'cannot parse invalid wire-format data'.

Update Python docs - fix doc issues with storage/bucket

---

src/pages/messaging.mdx

This noted limitation is no longer in place

docs: remove note about subscription loops

---

src/pages/sql.mdx

Migration files must include either .up.sql or .down.sql as an extension, this was indicated as optional originally.

docs: correct an error regarding correct migration file naming

---

dictionary.txt
src/nav.config.ts
src/pages/reference/providers/aws/configuration.mdx
src/pages/reference/providers/aws/imports.mdx

Documents changes from this PR https://github.com/nitrictech/nitric/pull/636 as well as the existing secrets import functionality

docs(aws): add resource imports docs

---

dictionary.txt
src/pages/faq.mdx
src/pages/reference/custom-containers.mdx

add some initial docs for monorepos with custom runtimes

add docs for monorepos

---

src/pages/getting-started/installation.mdx
src/pages/reference/cli/installation.mdx

Putting a note in to say pulumi is only required if using the default providers

adjust install prerequisites

---

src/pages/guides/python/serverless-rest-api-example.mdx

Guide still referenced a v0 property on returned values

doc: fix issue with python rest API guide

---

docs/guides/python/create-histogram.mdx
docs/guides/python/graphql.mdx
docs/guides/python/scheduled-report.mdx
docs/guides/python/serverless-rest-api-example.mdx
docs/guides/python/text-prediction.mdx

Update existing guides to use pipenv starter.
Will update to new uv starter in future

Update guides to pipenv python starter

---

docs/providers/pulumi/aws/configuration.mdx
docs/providers/pulumi/aws/index.mdx
docs/providers/terraform/aws.mdx

```
ephemeral-storage: 512
```

Update aws cfg ephemeral templates for pulumi and terraform

---

docs/apis.mdx
docs/reference/dart/api/api-all.mdx
docs/reference/dart/api/api-delete.mdx
docs/reference/dart/api/api-get.mdx
docs/reference/dart/api/api-patch.mdx
docs/reference/dart/api/api-post.mdx
docs/reference/dart/api/api-put.mdx
docs/reference/dart/api/api-route-all.mdx
docs/reference/dart/api/api-route-delete.mdx
docs/reference/dart/api/api-route-get.mdx
docs/reference/dart/api/api-route-patch.mdx
docs/reference/dart/api/api-route-post.mdx
docs/reference/dart/api/api-route-put.mdx
docs/reference/dart/api/api-route.mdx
docs/reference/dart/api/api.mdx
src/config/reference/dart.ts

Requires: https://github.com/nitrictech/dart-sdk/pull/33

feat: add dart middleware to api docs

---

docs/get-started/quickstart.mdx

Fix typo in the guides that still use pipenv for the default starter template.

docs: update python quickstart to use uv

---

docs/guides/nodejs/secure-api-auth0.mdx

In the edited curl command, no header is provided to show that the route requires authorization, and thus, no -H flag is needed; if run, it will fail as written.

Remove `-H` from curl command

---

dictionary.txt
docs/architecture/websites.mdx
docs/get-started/foundations/projects/configuration.mdx
docs/get-started/foundations/projects/local-development.mdx
docs/providers/mappings/aws/websites.mdx
docs/providers/mappings/azure/websites.mdx
docs/reference/preview-features/index.mdx
docs/websites.mdx
src/config/index.ts

add website docs

---

docs/reference/env.mdx

Closes https://github.com/nitrictech/docs/issues/707

add environment variable information

---

docs/guides/terraform/api-gateway-throttle.mdx
docs/guides/terraform/s3-encryption.mdx
docs/guides/terraform/s3-replicate.mdx
docs/guides/terraform/terratest.mdx
docs/guides/terraform/trivy.mdx
docs/providers/terraform/aws.mdx
docs/providers/terraform/azure.mdx
docs/providers/terraform/gcp.mdx
docs/providers/terraform/index.mdx

Should not be merged unless https://github.com/nitrictech/nitric/pull/771 is merged

docs: remove notes about the beta-providers preview flag

---

docs/reference/cli.mdx
docs/websites.mdx

Adds documentation for the new `nitric add` command,
including how to add websites and stacks to a project.
This provides users with clear instructions on how to use
the CLI to scaffold new resources.

feat: documents the add command

---

cypress/e2e/broken-links.cy.ts

Enhances the broken link checker by adding retry logic for rate limiting (429) and timeout (408) errors, using exponential backoff.
Introduces a mechanism to accept specific rate-limited URLs.
Processes links in batches to avoid overwhelming the system.
Skips checking empty or already visited URLs.

ci: improve broken link checker resilience

---

README.md

Consolidates documentation into the main repository.
This change improves maintainability, keeps documentation closer to the codebase, streamlines the development workflow, and provides a single source of truth for all Nitric resources.
Instructs users to update bookmarks and references to the new documentation location.

Archived documentation messaging
